# Generated by Django 2.2.13 on 2020-10-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcomment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
